### ISSUE TITLE
Error of SpireObject signature

### ISSUE THREAD

**Issue by MuhammadHammadBashir** [eiceblue/Spire.Presentation-for-Python#1]
plum.function.NotFoundLookupError: For function "__init__" of spire.presentation.common.SpireObject.SpireObject, signature Signature(spire.presentation.common.Image.Image) could not be resolved.

    image=Image(
  File "/usr/local/lib/python3.10/dist-packages/plum/function.py", line 642, in __call__
    return self.f(self.instance, *args, **kw_args)
  File "/usr/local/lib/python3.10/dist-packages/plum/function.py", line 591, in __call__
    method, return_type = self.resolve_method(*sig_types)
  File "/usr/local/lib/python3.10/dist-packages/plum/function.py", line 548, in resolve_method
    raise e
  File "/usr/local/lib/python3.10/dist-packages/plum/function.py", line 521, in resolve_method
    method, return_type = self._methods[self.resolve_signature(signature)]
  File "/usr/local/lib/python3.10/dist-packages/plum/function.py", line 492, in resolve_signature
    raise NotFoundLookupError(
plum.function.NotFoundLookupError: For function "__init__" of spire.presentation.common.SpireObject.SpireObject, signature Signature(spire.presentation.common.Image.Image) could not be resolved.

runner.exceptions.UnableToStartAppInstance
Exception ignored in: <function SpireObject.__del__ at 0x7fa1d67a6c20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/spire/presentation/common/SpireObject.py", line 31, in __del__
    CallCFunction(dlllib.Spire_FreeHandle,self.Ptr)
  File "/usr/local/lib/python3.10/dist-packages/spire/presentation/common/SpireObject.py", line 27, in Ptr
    return self._ptr
AttributeError: 'Image' object has no attribute '_ptr'

**Comment by eiceblue** [comment]
Hello, thanks for your interest in [Spire.Presentation for Python](https://www.e-iceblue.com/Introduce/presentation-for-python.html). Please refer to the following code snippet for testing after installing Pillow library. If you still have problems, please feel free to reply. 
```python
# pip install Pillow
from PIL import Image

image = Image.open("imageFile")
```

**Comment by lisali512** [comment]
thanks
