### ISSUE TITLE
Error saving slide as image: TypeInitialization_Type_NoTypeAvailable:   at 

### ISSUE THREAD

**Issue by sujianwei1** [eiceblue/Spire.Presentation-for-Python#2]
Error saving slide as image: TypeInitialization_Type_NoTypeAvailable:   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x167
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0xd
   at sprv83.spra(Size) + 0xf3
   at sprv83.sprk() + 0x66
   at sprv83.SaveAsImage() + 0xb
   at Spire.Presentation.AOT.NLISlide.ISlide_SaveAsImage1(IntPtr, IntPtr) + 0x4e
2024-10-18 16:17:55,249 - DEBUG - Traceback (most recent call last):
  File "c:\Users\70984\Desktop\pycode\aioffice\ts.py", line 23, in save_slide_as_image
    image = slide.SaveAsImage()
  File "C:\Users\70984\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\spire\presentation\ISlide.py", line 302, in SaveAsImage
    intPtr = CallCFunction(GetDllLibPpt().ISlide_SaveAsImage,self.Ptr)
  File "C:\Users\70984\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\spire\presentation\common\__init__.py", line 109, in CallCFunction
    raise SpireException(info)
spire.presentation.common.SpireException: TypeInitialization_Type_NoTypeAvailable:   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x167
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext*, IntPtr) + 0xd
   at sprv83.spra(Size) + 0xf3
   at sprv83.sprk() + 0x66
   at sprv83.SaveAsImage() + 0xb
   at Spire.Presentation.AOT.NLISlide.ISlide_SaveAsImage1(IntPtr, IntPtr) + 0x4e

**Comment by eiceblue** [comment]
Thank you for your interest in [Spire.Presentation for Python](https://www.e-iceblue.com/Introduce/presentation-for-python.html). I used the latest [Spire.Presentation for Python Version:10.1.0](https://www.e-iceblue.com/Download/Spire-Presentation-Python.html) to test slide to image conversion and did not encounter the problem you mentioned. As a suggestion, please upgrade to the latest version and retest. If your problem still exists, please reply to let us know. In addition, you can contact us via email @ support@e-iceblue.com, which is more efficient
